# Generated by Django 5.2.3 on 2025-07-03 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Receiver',
            new_name='Recipient',
        ),
    ]
