# Generated by Django 5.2.3 on 2025-08-02 05:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organ',
            fields=[
                ('organ_id', models.AutoField(primary_key=True, serialize=False)),
                ('organ_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='recipient',
            name='organ_needed',
        ),
        migrations.AddField(
            model_name='donor',
            name='matched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donor',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipient',
            name='matched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recipient',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='donor',
            name='age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='age',
            field=models.PositiveIntegerField(),
        ),
        migrations.CreateModel(
            name='MatchedTransplantation',
            fields=[
                ('transplantation_id', models.AutoField(primary_key=True, serialize=False)),
                ('donor_name', models.CharField(max_length=100)),
                ('recipient_name', models.CharField(max_length=100)),
                ('donor_blood_group', models.CharField(max_length=5)),
                ('recipient_blood_group', models.CharField(max_length=5)),
                ('matched_on', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.donor')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.recipient')),
                ('organ', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.organ')),
            ],
        ),
        migrations.AddField(
            model_name='recipient',
            name='organ',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.organ'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='organ',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.organ'),
        ),
    ]
