# Generated by Django 5.2.3 on 2025-08-02 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_organ_remove_recipient_organ_needed_donor_matched_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='aadhar',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='recipient',
            name='aadhar',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
