# Generated by Django 5.2.3 on 2025-09-18 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_contactsubmission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='aadhar',
        ),
        migrations.RemoveField(
            model_name='recipient',
            name='aadhar',
        ),
        migrations.AddField(
            model_name='donor',
            name='aadhar_image',
            field=models.ImageField(blank=True, null=True, upload_to='aadhar_images/'),
        ),
        migrations.AddField(
            model_name='donor',
            name='blood_report',
            field=models.FileField(blank=True, null=True, upload_to='blood_reports/'),
        ),
        migrations.AddField(
            model_name='recipient',
            name='aadhar_image',
            field=models.ImageField(blank=True, null=True, upload_to='aadhar_images/'),
        ),
        migrations.AddField(
            model_name='recipient',
            name='blood_report',
            field=models.FileField(blank=True, null=True, upload_to='blood_reports/'),
        ),
    ]
