# Generated by Django 5.2.3 on 2025-09-21 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_donor_aadhar_remove_recipient_aadhar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='aadhar_image',
            field=models.ImageField(default='', upload_to='aadhar_images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donor',
            name='blood_report',
            field=models.FileField(default='', upload_to='blood_reports/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipient',
            name='aadhar_image',
            field=models.ImageField(default='', upload_to='aadhar_images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipient',
            name='blood_report',
            field=models.FileField(default='', upload_to='blood_reports/'),
            preserve_default=False,
        ),
    ]
