# Generated by Django 5.2.3 on 2025-10-31 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_donor_aadhar_image_alter_donor_blood_report_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='aadhar_image',
            field=models.FileField(upload_to='aadhar_images/'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='aadhar_image',
            field=models.FileField(upload_to='aadhar_images/'),
        ),
    ]
